title = 'Isometric Game Blog'
baseurl = "https://zageron.ca"
languageCode = "en-us"
theme = "papermod"
paginate = 10

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
disableXML = true
minifyOutput = false

[params]
env = "production"
title = "Isometric Game Blog"
description = "Quick website to track my game development journey."
keywords = ["GameDev", "Blog", "Rust"]
author = "Zageron"
DateFormat = "Monday, January 02, 2006 15:04"
defaultTheme = "dark"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = true
showtoc = false
tocopen = false

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my Isometric Game blog!"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/@zageron"

[[params.socialIcons]]
name = "github"
url = "https://github.com/zageron"

[[params.socialIcons]]
name = "rss"
url = "index.xml"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/Zageron/blog/tree/main/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[taxonomies]
series = "series"
tag = "tags"

[[menu.main]]
identifier = "series"
name = "series"
url = "/series/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 30
