name: github pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".git*"
      - ".vscode"
      - "LICENCE"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true
          fetch-depth: 0
          lfs: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --enableGitInfo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: zageron.ca
