name: Deploy Hugo

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".git*"
      - ".vscode"
      - "LICENCE"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          lfs: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "latest"
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5.0.0

      - name: Build
        run: |
          hugo \
          --minify \
          --enableGitInfo
          --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./public

  deploy-pages:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
