name: github pages

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.git*'
      - '.vscode'
      - 'LICENCE'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: true
          fetch-depth: 0
          lfs: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --enableGitInfo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: zageron.ca
